server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://114.55.227.97:3306/fiance_fiance?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fiance
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 1


  mvc:
    throw-exception-if-no-handler-found=true:
knife4j:
  enable: true
token:
  key: 8848