server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://192.168.3.19:3306/fiance_fiance?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 1
  mvc:
    throw-exception-if-no-handler-found=true:

  boot:
    admin:
      client:
        url: http://localhost:9000
        instance:
          prefer-ip: true
  application:
    name: admin

knife4j:
  enable: true
token:
  key: 8848




#  endpoints config
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: client.log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl