server:
  port: 8093

spring:
  datasource:
    url: jdbc:mysql://192.168.3.19:3306/fiance_fiance?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fiance
    password: 123456
  redis:
    host: localhost
    port: 6379
  messages:
    basename: i18n.messages
    encoding: UTF-8

knife4j:
  enable: true
mybatis-plus:
  configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

